version: "3"

services:
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "32770:5432"
    environment:
      POSTGRES_DATABASE: shop
      POSTGRES_USER: tom
      POSTGRES_PASSWORD: tom
  web:
    build: .
    image: halvong/autoshop-django
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    #command: >
    #  gunicorn -b 0.0.0.0:8000
    #    --access-logfile -
    #    --reload
    #    wisdompets.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
volumes:
  db-data:
